name: integration-testing-generator

on:
  workflow_call:
    inputs:
      branch:
        type: string
        required: true
      tag:
        type: string
        required: true
  workflow_dispatch:
    inputs:
      branch:
        description: 'integration testing from'
        required: true
        default: 'master'
      tag:
        description: 'govite tag prefix'
        required: true
        default: 'v2.11.0'

jobs:
  build:
    runs-on: ubuntu-18.04
    steps:
    # Inconsistent inputs context for workflow_dispatch and workflow_call
    - name: Set branch and tag
      id: step0
      run: |
        echo "::set-output name=branch::${{ (inputs || github.event.inputs).branch }}"
        echo "::set-output name=tag::${{ (inputs || github.event.inputs).tag }}"

    - name: Echo branch and tag
      run: echo ${{ steps.step0.outputs.branch }} ${{ steps.step0.outputs.tag }}

    - name: Set LedgerFile Version
      id: version
      run: echo "::set-output name=version::$(date +%Y%m%d%H%M)"

    - uses: actions/checkout@v2
      with:
        repository: 'vitelabs/go-vite-nightly'
        ref: '${{ steps.step0.outputs.branch }}'
        path: go-vite-nightly

    - name: Run Gvite Node
      run: |
        ./go-vite-nightly/gvite-cluster/boot

    - name: Setup Node
      uses: actions/setup-node@v2.1.2
      with:
        node-version: 'v16'
    - name: Run Data Generator
      run: |
        pwd
        cd go-vite-nightly/integration-testing
        npm install
        npx ts-node scripts/generator.ts
        cd ../../
        mkdir ledger
        docker cp gvite-cluster_s1_1:/root/.gvite/node1/devdata/ledger/blocks ledger
        ls -al ledger/*
        tar cvf ledger.tar.gz ledger/blocks 
        ls -al

    - name: Release
      uses: ncipollo/release-action@v1
      with:
        tag: "${{ steps.step0.outputs.tag }}-ledgerfile-${{ steps.version.outputs.version }}"
        artifacts: "ledger.tar.gz"
        token: ${{ secrets.GITHUB_TOKEN }}

    - name: Post Gvite Node
      run: |
        ./go-vite-nightly/gvite-cluster/shutdown

       
      