name: integration-testing

on:
  workflow_call:
    inputs:
      branch:
        type: string
        required: true
  workflow_dispatch:
    inputs:
      branch:
        description: 'integration testing from'
        required: true

jobs:
  build:
    runs-on: ubuntu-18.04
    steps:
    # Inconsistent inputs context for workflow_dispatch and workflow_call
    - name: Set branch and tag
      id: step0
      run: |
        echo "::set-output name=branch::${{ (inputs || github.event.inputs).branch }}"
        echo "::set-output name=tag::${{ (inputs || github.event.inputs).tag }}"

    - name: Echo branch and tag
      run: echo ${{ steps.step0.outputs.branch }} ${{ steps.step0.outputs.tag }}

    - uses: actions/checkout@v2
      with:
        repository: 'vitelabs/go-vite'
        ref: '${{ steps.step0.outputs.branch }}'
        path: go-vite

    - uses: actions/checkout@v2
      with:
        repository: 'vitelabs/go-vite-nightly'
        ref: '${{ steps.step0.outputs.branch }}'
        path: go-vite-nightly

    - name: Set up Go
      uses: actions/setup-go@v2
      with:
        go-version: 1.16

    - name: Make && Docker Image
      run: |
        pwd
        cd go-vite
        make test
        make gvite-linux
        docker build -t vitelabs/gvite-nightly:test . -f docker/Dockerfile.preBuild

    - name: Fetch ledgerfile
      run: |   
        pwd 
        apt-get install jq -y
        cd go-vite-nightly/integration-testing/scripts
        wget `cat result.json | jq -r '.url'`
        tar xvf ledger.tar.gz
        cp ../../gvite-cluster/genesis.json ledger
        cp ../../gvite-cluster/node_config.json ledger

    - name: Run Docker
      run: |
        docker run -d -v ledger:/root/.gvite -p 127.0.0.1:48132:48132  --rm vitelabs/gvite-nightly:test --config /root/.gvite/node_config.json load --fromDir=/root/.gvite

    - name: Check Result
      run: |
        pwd
        cd go-vite-nightly/integration-testing
        npm install
        npx vuilder test scripts/check_result.ts

       
      