name: integration-testing

on:
  workflow_call:
    inputs:
      branch:
        type: string
        required: true
  workflow_dispatch:
    inputs:
      branch:
        description: 'integration testing from'
        required: true
        default: 'master'

jobs:
  build:
    runs-on: ubuntu-18.04
    steps:
    # Inconsistent inputs context for workflow_dispatch and workflow_call
    - name: Set branch and tag
      id: step0
      run: |
        echo "::set-output name=branch::${{ (inputs || github.event.inputs).branch }}"
        echo "::set-output name=tag::${{ (inputs || github.event.inputs).tag }}"

    - name: Echo branch and tag
      run: echo ${{ steps.step0.outputs.branch }} ${{ steps.step0.outputs.tag }}

    - uses: actions/checkout@v2
      with:
        repository: 'vitelabs/go-vite'
        ref: '${{ steps.step0.outputs.branch }}'
        path: go-vite

    - uses: actions/checkout@v2
      with:
        repository: 'vitelabs/go-vite-nightly'
        ref: '${{ steps.step0.outputs.branch }}'
        path: go-vite-nightly

    - name: Set up Go
      uses: actions/setup-go@v2
      with:
        go-version: 1.16

    - name: Make && Docker Image
      run: |
        pwd
        cd go-vite
        make test
        make gvite-linux
        cp build/cmd/gvite/gvite-*-linux/gvite ../gvite-testing

    - name: Fetch gvite ledger file
      run: |   
        pwd 
        cd gvite-testing
        sudo apt-get install jq -y
        wget -c `cat ../go-vite-nightly/integration-testing/scripts/result.json | jq -r '.url'`
        tar xvf ledger.tar.gz && rm ledger.tar.gz
        pwd
        ls -al *
        docker build -t vitelabs/gvite-nightly:test .

    - name: Run Docker
      run: |
        pwd
        cd testing
        ls -al /home/runner/work/go-vite-nightly/go-vite-nightly/testing/ledger/*
        docker run -d -p 127.0.0.1:48132:48132  vitelabs/gvite-nightly:test --config /root/node_config.json load --fromDir=/root/ledger
        sleep 10
        docker ps -a
        ls -al ledger/*

#     - name: Check Result
#       run: |
#         pwd
#         cd go-vite-nightly/integration-testing
#         npm install
#         npx ts-node scripts/check_result.ts

       
      
