name: handle-dispatch-event

on:
  repository_dispatch:
    types: [nightly-build-event]
  workflow_dispatch:
    inputs:
      branch:
        default: master
        description: 'nightly build from'
        required: true
      tag:
        default: v0.0.0
        description: 'tag prefix'
        required: true

jobs:
  trigger_build:
    uses: ./.github/workflows/govite-nightly-build.yml
    with:
      branch: ${{ github.event.client_payload.branch || github.event.inputs.branch }}
      tag: ${{ github.event.client_payload.tag || github.event.inputs.tag }}